### ISSUE TITLE
Device type not set even if it is

### ISSUE THREAD

**Issue by olemis** [skycoin/hardware-wallet-go#90] opened 2019-04-04 01:02 UTC
**Describe the bug**
A clear and concise description of the problem and bug effects.

**Environment information:**

- OS: `osx`
- Platform: Darwin 17.4.0 x86_64
- Library version : at current `master` 6ec9e64fc6de1579318631eab01105f9516431ef
- Firmware Version: at current `develop` `b6846cbf353f96870de8b7fb9857a1b4b14640f8`

**Steps to Reproduce**

With dev environment setup then run

```
$ go run cmd/cli/cli.go signMessage --addressN 0 message "1234567890" --deviceType EMULATOR
$ go run cmd/cli/cli.go --deviceType EMULATOR signMessage --addressN 0 message "1234567890"
```

**Actual behavior**

First command returns `[2019-04-03T20:48:43-04:00] ERROR [device-wallet]: device type not set, valid options are USB or EMULATOR` whereas the second leads to

```
Error: flag provided but not defined: -deviceType

NAME:
   skycoin-hw-cli - the skycoin hardware wallet command line interface

USAGE:
   cli [global options] command [command options] [arguments...]

VERSION:
   1.7.0

COMMANDS:
     applySettings          Apply settings.
     setMnemonic            Configure the device with a mnemonic.
     features               Ask the device Features.
     generateMnemonic       Ask the device to generate a mnemonic and configure itself with it.
     addressGen             Generate skycoin addresses using the firmware
     firmwareUpdate         Update device's firmware.
     signMessage            Ask the device to sign a message using the secret key at given index.
     checkMessageSignature  Check a message signature matches the given address.
     setPinCode             Configure a PIN code on a device.
     wipe                   Ask the device to wipe clean all the configuration it contains.
     backup                 Ask the device to perform the seed backup procedure.
     recovery               Ask the device to perform the seed recovery procedure.
     cancel                 Ask the device to cancel the ongoing procedure.
     transactionSign        Ask the device to sign a transaction using the provided information.
     sandbox                Sandbox.
     help, h                Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

**Expected behavior**
signed message

**Comment by olemis** [comment] 2019-04-04 01:05
The second command invocation is correct , btw

**Comment by therealssj** [comment] 2019-04-07 09:21
@olemis i can't reproduce this.
The second invocation is incorrect. 
The correct invocation is:
```
$ DEVICE_TYPE=EMULATOR go run cmd/cli/cli.go signMessage --addressN 0 message "1234567890"
```

Im closing this for now

**Closed by therealssj** 2019-04-07 09:21 UTC
Labels: bug
